name: VBA GX Build

on: [push, pull_request]

jobs:
  build:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build
      run: |
        make -j2

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with: 
        name: executables
        path: executables/*
