name: VBA GX Build

on: [push, pull_request]

jobs:
  build:
    name: ubuntu-20.04
    runs-on: ubuntu-20.04
    container: devkitpro/devkitppc:latest
 
    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true

    - name: Build
      run: |
        make -j2
    
    - name: Copy files
      run: | 
        mkdir -p dist/VisualBoyAdvanceGX/apps/vbagx
        mkdir -p dist/VisualBoyAdvanceGX/vbagx/roms
        mkdir dist/VisualBoyAdvanceGX/vbagx/saves
        mkdir dist/VisualBoyAdvanceGX-GameCube/
        cp hbc/* dist/VisualBoyAdvanceGX/apps/vbagx/
        cp executables/vbagx-wii.dol dist/VisualBoyAdvanceGX/apps/vbagx/boot.dol
        cp executables/vbagx-gc.dol dist/VisualBoyAdvanceGX-GameCube/

    - name: Upload Wii Build Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: VisualBoyAdvanceGX-Nightly
        path: |
         dist/VisualBoyAdvanceGX/
    
    - name: Upload GameCube Build Artifacts
      uses: actions/upload-artifact@v2
      with: 
        name: VisualBoyAdvanceGX-Nightly-GameCube
        path: |
         dist/VisualBoyAdvanceGX-GameCube/
